Metadata:
  TemplateId: "arn:aws:cloudformation:us-east-1:173679718835:generatedTemplate/2e473773-a999-442c-880e-0cf99f376237"
Resources:
  # IAM policy for accessing CodeArtifact
  IAMManagedPolicy00policycodeartifactnextworkconsumerpolicy00VzYGj:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole200EjgPv"
    Properties:
      ManagedPolicyName: "codeartifact-nextwork-consumer-policy"
      Path: "/"
      Description: "Provides permissions to read from CodeArtifact."
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: "*"
            Action:
              - "codeartifact:GetAuthorizationToken"
              - "codeartifact:GetRepositoryEndpoint"
              - "codeartifact:ReadFromRepository"
            Effect: "Allow"
          - Condition:
              StringEquals:
                sts:AWSServiceName: "codeartifact.amazonaws.com"
            Resource: "*"
            Action: "sts:GetServiceBearerToken"
            Effect: "Allow"
      Roles:
        - "codebuild-nextwork-web-build-service-role-2"
      Users: []

  # S3 bucket
  S3Bucket00nextworkbuildartifactszandile00pGqTF:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole200EjgPv"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "nextwork-build-artifacts-zandile"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  # CodeBuild service role
  IAMRole00codebuildnextworkwebbuildservicerole200EjgPv:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    Properties:
      Path: "/service-role/"
      MaxSessionDuration: 3600
      RoleName: "codebuild-nextwork-web-build-service-role-2"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"

  # CodeArtifact domain
  CodeArtifactDomain00domainnextwork00zJRHp:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Domain"
    DeletionPolicy: "Delete"
    Properties:
      DomainName: "nextwork"

  # CodeArtifact local repository
  CodeArtifactRepository00repositorynextworknextworkpackages004BvdT:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      Upstreams:
        - Fn::GetAtt:
            - "CodeArtifactRepository00repositorynextworkmavencentralstore00CwNeH"
            - "Name"
      RepositoryName: "nextwork-packages"
      Description: "Packages for the NextWork web app."
      DomainName:
        Fn::GetAtt:
          - "CodeArtifactDomain00domainnextwork00zJRHp"
          - "Name"

  # IAM Policy for CodeBuild's basic permissions
  IAMManagedPolicy00policyserviceroleCodeBuildBasePolicycodebuildnextworkwebbuildservicerole2useast100k7ecL:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole200EjgPv"
    Properties:
      ManagedPolicyName: "CodeBuildBasePolicy-codebuild-nextwork-web-build-service-role-2-us-east-1"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource:
              - "arn:aws:logs:us-east-1:173679718835:log-group:/aws/codebuild/nextwork-web-build"
              - "arn:aws:logs:us-east-1:173679718835:log-group:/aws/codebuild/nextwork-web-build:*"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Effect: "Allow"
          - Resource:
              - "arn:aws:s3:::codepipeline-us-east-1-*"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:GetObjectVersion"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
            Effect: "Allow"
          - Resource:
              - "arn:aws:codecommit:us-east-1:173679718835:nextwork-web-project"
            Action:
              - "codecommit:GitPull"
            Effect: "Allow"
          - Resource:
              - "arn:aws:s3:::nextwork-build-artifacts-zandile"
              - "arn:aws:s3:::nextwork-build-artifacts-zandile/*"
            Action:
              - "s3:PutObject"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
            Effect: "Allow"
          - Resource:
              - "arn:aws:codebuild:us-east-1:173679718835:report-group/nextwork-web-build-*"
            Action:
              - "codebuild:CreateReportGroup"
              - "codebuild:CreateReport"
              - "codebuild:UpdateReport"
              - "codebuild:BatchPutTestCases"
              - "codebuild:BatchPutCodeCoverages"
            Effect: "Allow"
      Roles:
        - "codebuild-nextwork-web-build-service-role-2"
      Users: []

  # CodeArtifact upstream repository
  CodeArtifactRepository00repositorynextworkmavencentralstore00CwNeH:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      RepositoryName: "maven-central-store"
      Description: "Provides Maven artifacts from Maven Central Repository."
      ExternalConnections:
        - "public:maven-central"
      DomainName:
        Fn::GetAtt:
          - "CodeArtifactDomain00domainnextwork00zJRHp"
          - "Name"

  # CodeCommit Repository
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: nextwork-web-project
      RepositoryDescription: "A web application for the NextWork home page"

  # CodeBuild Project
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: nextwork-web-build
      Description: "Build project for NextWork web application"
      Source:
        Type: CODECOMMIT
        Location: !GetAtt CodeCommitRepository.CloneUrlHttp
        BuildSpec: "buildspec.yml"
      Artifacts:
        Type: S3
        Name: "nextwork-web-build.zip"
        Packaging: ZIP
        Location: !Ref S3Bucket00nextworkbuildartifactszandile00pGqTF
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:corretto8"
      ServiceRole: !GetAtt IAMRole00codebuildnextworkwebbuildservicerole200EjgPv.Arn
      LogsConfig:
        CloudWatchLogs:
          GroupName: "nextwork-build-logs"
          Status: "ENABLED"
          StreamName: "webapp"